// <auto-generated />
using System;
using Doan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Doan.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Doan.Models.BinhLuanModel", b =>
                {
                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("MaPhim");

                    b.HasIndex("Username");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("Doan.Models.GheModel", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<int?>("LichChieu")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaGhe");

                    b.HasIndex("LichChieu");

                    b.HasIndex("MaPhong");

                    b.ToTable("Ghe");
                });

            modelBuilder.Entity("Doan.Models.HoaDonModel", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VeDaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHD");

                    b.HasIndex("Username");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Doan.Models.LichChieuModel", b =>
                {
                    b.Property<int>("MaLichChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGheTrong")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("maphim")
                        .HasColumnType("int");

                    b.HasKey("MaLichChieu");

                    b.HasIndex("MaPhong");

                    b.HasIndex("maphim");

                    b.ToTable("LichChieu");
                });

            modelBuilder.Entity("Doan.Models.PhimModel", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DaoDien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Theloai")
                        .HasColumnType("int");

                    b.Property<string>("ThoiLuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhim");

                    b.HasIndex("Theloai");

                    b.ToTable("Phim");
                });

            modelBuilder.Entity("Doan.Models.PhongChieuModel", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SoGhe")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongChieu");
                });

            modelBuilder.Entity("Doan.Models.TaiKhoanModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Doan.Models.TheloaiModel", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("Doan.Models.VeModel", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<int?>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiMua")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SuatChieu")
                        .HasColumnType("int");

                    b.HasKey("MaVe");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.HasIndex("NguoiMua");

                    b.HasIndex("SuatChieu");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("Doan.Models.BinhLuanModel", b =>
                {
                    b.HasOne("Doan.Models.PhimModel", "phim")
                        .WithMany()
                        .HasForeignKey("MaPhim");

                    b.HasOne("Doan.Models.TaiKhoanModel", "taikhoan")
                        .WithMany()
                        .HasForeignKey("Username");

                    b.Navigation("phim");

                    b.Navigation("taikhoan");
                });

            modelBuilder.Entity("Doan.Models.GheModel", b =>
                {
                    b.HasOne("Doan.Models.LichChieuModel", "lichchieu")
                        .WithMany()
                        .HasForeignKey("LichChieu");

                    b.HasOne("Doan.Models.PhongChieuModel", "phong")
                        .WithMany()
                        .HasForeignKey("MaPhong");

                    b.Navigation("lichchieu");

                    b.Navigation("phong");
                });

            modelBuilder.Entity("Doan.Models.HoaDonModel", b =>
                {
                    b.HasOne("Doan.Models.TaiKhoanModel", "taikhoan")
                        .WithMany()
                        .HasForeignKey("Username");

                    b.Navigation("taikhoan");
                });

            modelBuilder.Entity("Doan.Models.LichChieuModel", b =>
                {
                    b.HasOne("Doan.Models.PhongChieuModel", "phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doan.Models.PhimModel", "phim")
                        .WithMany()
                        .HasForeignKey("maphim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("phim");

                    b.Navigation("phong");
                });

            modelBuilder.Entity("Doan.Models.PhimModel", b =>
                {
                    b.HasOne("Doan.Models.TheloaiModel", "theloai")
                        .WithMany()
                        .HasForeignKey("Theloai");

                    b.Navigation("theloai");
                });

            modelBuilder.Entity("Doan.Models.VeModel", b =>
                {
                    b.HasOne("Doan.Models.GheModel", "ghe")
                        .WithMany()
                        .HasForeignKey("MaGhe");

                    b.HasOne("Doan.Models.PhimModel", "phim")
                        .WithMany()
                        .HasForeignKey("MaPhim");

                    b.HasOne("Doan.Models.PhongChieuModel", "phong")
                        .WithMany()
                        .HasForeignKey("MaPhong");

                    b.HasOne("Doan.Models.TaiKhoanModel", "taikhoan")
                        .WithMany()
                        .HasForeignKey("NguoiMua");

                    b.HasOne("Doan.Models.LichChieuModel", "lichchieu")
                        .WithMany()
                        .HasForeignKey("SuatChieu");

                    b.Navigation("ghe");

                    b.Navigation("lichchieu");

                    b.Navigation("phim");

                    b.Navigation("phong");

                    b.Navigation("taikhoan");
                });
#pragma warning restore 612, 618
        }
    }
}
