// <auto-generated />
using System;
using CinemaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaWeb.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Doan.Models.BinhLuanModel", b =>
                {
                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(50)");

                    b.HasIndex("MaPhim");

                    b.HasIndex("Username");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("Doan.Models.GheModel", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaGhe");

                    b.HasIndex("MaPhong");

                    b.ToTable("Ghe");
                });

            modelBuilder.Entity("Doan.Models.HoaDonModel", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VeDaDat")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaHD");

                    b.HasIndex("Username");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Doan.Models.LichChieuModel", b =>
                {
                    b.Property<int>("MaLichChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("Date");

                    b.Property<int>("SoGheTrong")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ThoiGian")
                        .HasColumnType("Time");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLichChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("LichChieu");
                });

            modelBuilder.Entity("Doan.Models.PhimModel", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DaoDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TheLoai")
                        .HasColumnType("int");

                    b.Property<string>("ThoiLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhim");

                    b.HasIndex("TheLoai");

                    b.ToTable("Phim");
                });

            modelBuilder.Entity("Doan.Models.PhongChieuModel", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SoGhe")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongChieu");
                });

            modelBuilder.Entity("Doan.Models.TaiKhoanModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiTK")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Username");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Doan.Models.TheloaiModel", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoai");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("Doan.Models.VeModel", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GiaVe")
                        .HasColumnType("int");

                    b.Property<int?>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("date");

                    b.Property<string>("NguoiMua")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SuatChieu")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaVe");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.HasIndex("NguoiMua");

                    b.HasIndex("SuatChieu");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("Doan.Models.BinhLuanModel", b =>
                {
                    b.HasOne("Doan.Models.PhimModel", "maphim")
                        .WithMany()
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doan.Models.TaiKhoanModel", "username")
                        .WithMany()
                        .HasForeignKey("Username");

                    b.Navigation("maphim");

                    b.Navigation("username");
                });

            modelBuilder.Entity("Doan.Models.GheModel", b =>
                {
                    b.HasOne("Doan.Models.PhongChieuModel", "maphong")
                        .WithMany("lstGhe")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("maphong");
                });

            modelBuilder.Entity("Doan.Models.HoaDonModel", b =>
                {
                    b.HasOne("Doan.Models.TaiKhoanModel", "username")
                        .WithMany("ListHoaDon")
                        .HasForeignKey("Username");

                    b.Navigation("username");
                });

            modelBuilder.Entity("Doan.Models.LichChieuModel", b =>
                {
                    b.HasOne("Doan.Models.PhimModel", "maphim")
                        .WithMany()
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doan.Models.PhongChieuModel", "maphong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("maphim");

                    b.Navigation("maphong");
                });

            modelBuilder.Entity("Doan.Models.PhimModel", b =>
                {
                    b.HasOne("Doan.Models.TheloaiModel", "theloai")
                        .WithMany("ListPhim")
                        .HasForeignKey("TheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("theloai");
                });

            modelBuilder.Entity("Doan.Models.VeModel", b =>
                {
                    b.HasOne("Doan.Models.GheModel", "maghe")
                        .WithMany()
                        .HasForeignKey("MaGhe");

                    b.HasOne("Doan.Models.PhimModel", "maphim")
                        .WithMany()
                        .HasForeignKey("MaPhim");

                    b.HasOne("Doan.Models.PhongChieuModel", "maphong")
                        .WithMany()
                        .HasForeignKey("MaPhong");

                    b.HasOne("Doan.Models.TaiKhoanModel", "nguoimua")
                        .WithMany()
                        .HasForeignKey("NguoiMua");

                    b.HasOne("Doan.Models.LichChieuModel", "lichchieu")
                        .WithMany()
                        .HasForeignKey("SuatChieu");

                    b.Navigation("lichchieu");

                    b.Navigation("maghe");

                    b.Navigation("maphim");

                    b.Navigation("maphong");

                    b.Navigation("nguoimua");
                });

            modelBuilder.Entity("Doan.Models.PhongChieuModel", b =>
                {
                    b.Navigation("lstGhe");
                });

            modelBuilder.Entity("Doan.Models.TaiKhoanModel", b =>
                {
                    b.Navigation("ListHoaDon");
                });

            modelBuilder.Entity("Doan.Models.TheloaiModel", b =>
                {
                    b.Navigation("ListPhim");
                });
#pragma warning restore 612, 618
        }
    }
}
